# NumPy - podstawy

Moduł NumPy stanowi element większego pakietu o nazwie SciPy, zawierającego moduły NumPy, SciPy, matplotlib, IPython oraz SymPy. Pełen pakiet SciPy ma pełną funkcjonalność Octave, a nawet go przewyższa. Dystrybucja Anaconda, której używamy na zajęciach, jest przystosowana właśnie do pracy z pakietem SciPy (w szczególności nie ma potrzeby doinstalowywania żadnych modułów).

Sprawdźmy, czy tak jest faktycznie.

In [1]:
import numpy

Brak modułu zostałby zasygnalizowany komunikatem błedu

 `ImportError: No module named 'numpy'`

## Macierz ndarray - tworzenie ,,ręczne''

Kluczowym obiektem w module NumPy jest `ndarray`, czyli $n$-wymiarowa macierz elementów tego samego typu. Tworzymy go za pomocą funkcji `array` z modułu `numpy`. Pełen przykładowy konstruktor obiektu `ndarray` wygląda następująco:

```python
numpy.array(obiekt, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
gdzie poszczególne parametry to:
- `obiekt` - obiekt, który chcemy przetworzyć na macierz, np. lista znaków `[1,2,3,4]` lub innych elementów
- `dtype` - opcjonalnie, wymuszony końcowy typ elementów macierzy
- `copy` - opcjonalnie (domyślna wartość `True`), wymusza kopiowanie obiektu przetwarzanego na macierz
- `order` - opcjonalnie, kolejność indeksacji w pamięci: `C` - najpierw wiersze (jak w C/C++), `F` - najpierw kolumny (jak w Fortranie), `A` - (domyślnie) jakkolwiek
- `subok` - opcjonalnie, domyślne ustawienie `False`, ustawienie `True` dopuszcza użycie podklas
- `ndmin` - opcjonalnie, określa minimalny wymiar otrzymanej macierzy

Przykładowo:

In [2]:
import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([1,2,3,4,5],dtype=complex)
C = np.array([1,2,3,4,5],ndmin=2)
print(A)
print(B)
print(C)

[1 2 3 4 5]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
[[1 2 3 4 5]]


Macierz dwuwymiarową tworzymy następująco:

In [3]:
D=np.array([[1,2],[3,4],[5,6]])
print(D)

[[1 2]
 [3 4]
 [5 6]]


## "Automatyczne" tworzenie macierzy

- `numpy.arange(n)` tworzy wiersz liczb od 0 do $n$
- `numpy.arange(start,end,step)` tworzy wiersz liczb od `start` (włącznie) do `end` (nie włącznie) oddalonych o `step`
- `numpy.linspace(start,end,n)` tworzy wiersz $n$ liczb rozłożonych równomiernie od `start` do `end` **włącznie**
- `numpy.ones((n,m))` - macierz wymiaru $n\times m$ wypełniona jedynkami
- `numpy.zeros((n,m))` - macierz wymiaru $n\times m$ wypełniona zerami
- `numpy.eye(n)` - jednostkowa macierz kwadratowa wymiaru $n\times n$
- `numpy.diag(numpy.array([1, 2, 3, 4]))` - macierz, która na przekątnej ma elementy 1,2,3,4, pozostałe miejsca to zera
- `numpy.random.rand(n)` - wiersz $n$ liczb losowych z przedziału $[0,1]$
- `numpy.random.randn(n)` - wiersz $n$ liczb losowych o rozkładzie Gaussa

## Nawigacja i podstawowe operacje na macierzach

Załóżmy, że mamy macierze

In [4]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,1],[0,-1]])
C=np.array([1,2,3,4])
D=np.array([[1,2],[2,1],[3,2]])

- `A.ndim` zwraca liczbę wymiarów macierzy
- `len(A)` zwraca liczbę elementów w macierzy jednowymiarowej lub liczbę elementów w pierwszym wymiarze macierzy dwuwymiarowej (tzn. liczbę wierszy)
- `A.shape` zwraca wymiar macierzy
- `C.reshape(n,m)` utworzy z wektora C macierz wymiaru $n\times m$
- `A.flatten()` zwraca wektor utworzony z elementów macierzy A, w kolejności elementów w wierszach (domyślnie, `order='C'`) lub przy `order='F'` - w kolumnach

In [5]:
print(A.ndim)
print(D.ndim)

2
2


In [6]:
print(len(C))
print(len(D))
print(A.shape)
print(C.reshape(2,2))
print(D)
print(D.flatten())
print(D.flatten(order='F'))

4
3
(2, 2)
[[1 2]
 [3 4]]
[[1 2]
 [2 1]
 [3 2]]
[1 2 2 1 3 2]
[1 2 3 2 1 2]


- `C[n]` zwraca $n+1$ element wiersza (pamiętamy: numeracja zaczyna się od 0)
- `A[n,m]` zwraca element w $n+1$ wierszu i $m+1$ kolumnie
- `A[n]` zwraca $n+1$ wiersz
- `C[start:end:n]` zwraca co $n$-ty element wiersza C, począwszy od miejsca `start` do miejsca `end` nie włącznie
- `C[::-1]` szybkie odwrócenie kolejności elementów w wierszu C
- dla macierzy wielowymiarowych działa połączenie powyższych operacji, np. `A[0:2,0]` zwróci wektor `[1,3]` (tzn. elementy w pierwszej kolumnie, w wierszach 0 i 1)

In [7]:
print(A[0,0])
print(D[1])    #drugi wiersz
print(D[:,1])  #druga kolumna

1
[2 1]
[2 1 2]


- dodawanie macierzy: `A+B`
- mnożenie macierzy miejsce w miejsce: `A*B`
- mnożenie macierzy: `A.dot(B)`
- `A+2` - dodaje do każdego elementu macierzy liczbę 2
- `A.T` lub `numpy.transpose(A)` - transpozycja
- `numpy.sum(A)` lub `A.sum()` zwraca sumę wszystkich elementów macierzy
- `A.sum(axis=0)` zwraca macierz złożoną z sum po pierwszym wymiarze macierzy $A$ (dla drugiego wymiaru `axis=1`)
- `A.min()` - najmniejszy element w macierzy (dla największego - `max`)
- `A.argmin()` - indeks najmniejszego elementu w macierzy
- `numpy.linalg.eig(A)` oblicza wartości własne oraz (prawe) wektory własne macierzy

## Zadanie 1.

 Napisać skrypt tworzący macierz o wymiarach $n\times n$, która poniżej głównej przekątnej ma zera, na głównej przekątnej jedynki, na drugiej przekątnej dwójki, na trzeciej trójki itp.

In [8]:
def creator(n):
    zad1=np.zeros([n,n])
    for i in range(n+1):
        zad1=zad1+np.diag([i for _ in range(n)],i-1)[:n,:n]
    return zad1
print(creator(4))

[[1. 2. 3. 4.]
 [0. 1. 2. 3.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]]


## Zadanie 2.

Utworzyć macierz $10\times 10$ wypełnioną kolejno liczbami od 0 do 99. Za pomocą odpowiednich operacji wyciąć z niej następujące macierze:
- wektor elementów od 20 do 29
- macierz elementów od 30 do 59
- macierz składającą się z wszystkich liczb parzystych od 20 do 89

In [9]:
zad2=np.arange(0,100,1).reshape([10,10])
print(zad2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [10]:
zad2[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
zad2[3:6,:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [12]:
zad2[2:9,[x for x in range(0,10,2)]]

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88]])

## Zadanie 3.

Za pomocą operacji na wierszach i kolumnach wygenerować następującą macierz

 $$\left[\begin{matrix}
          1&2&3&4&5&6&7&8&9&0\\
          2&2&3&4&5&6&7&8&9&0\\
          3&3&3&4&5&6&7&8&9&0\\
          4&4&4&4&5&6&7&8&9&0\\
          5&5&5&5&5&6&7&8&9&0\\
          6&6&6&6&6&6&7&8&9&0\\
          7&7&7&7&7&7&7&8&9&0\\
          8&8&8&8&8&8&8&8&9&0\\
          9&9&9&9&9&9&9&9&9&0\\
          0&0&0&0&0&0&0&0&0&0
         \end{matrix}\right]$$

In [13]:
zad3=np.zeros([10,10])
for i in range(0,9):
    zad3[:,i]=i+1
zad3t=zad3.T
for i in range(0,10):
    for j in range(0,10):
        if i<j:
            zad3[j,i]=zad3t[j,i]
zad3

array([[1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [2., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [3., 3., 3., 4., 5., 6., 7., 8., 9., 0.],
       [4., 4., 4., 4., 5., 6., 7., 8., 9., 0.],
       [5., 5., 5., 5., 5., 6., 7., 8., 9., 0.],
       [6., 6., 6., 6., 6., 6., 7., 8., 9., 0.],
       [7., 7., 7., 7., 7., 7., 7., 8., 9., 0.],
       [8., 8., 8., 8., 8., 8., 8., 8., 9., 0.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])